use_frameworks!
source 'https://github.com/iFlyCai/IFLYSpecs.git' # 私有库的 Podspec 仓库
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '16.0'

target 'YYTextDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'IFLYCommonKitObjc'

end
